# Generated by Django 2.1 on 2019-05-29 22:52

from django.db import migrations, models
import django.db.models.deletion
import stock.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleTurno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejemplar', models.IntegerField(verbose_name=stock.models.Ejemplar)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTurno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaTurno', models.DateTimeField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Cancelado',
            fields=[
                ('estadoturno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turno.EstadoTurno')),
            ],
            bases=('turno.estadoturno',),
        ),
        migrations.CreateModel(
            name='PorRetirar',
            fields=[
                ('estadoturno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turno.EstadoTurno')),
            ],
            bases=('turno.estadoturno',),
        ),
        migrations.CreateModel(
            name='Retirado',
            fields=[
                ('estadoturno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turno.EstadoTurno')),
            ],
            bases=('turno.estadoturno',),
        ),
        migrations.AddField(
            model_name='turno',
            name='estadoTurno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turno.EstadoTurno'),
        ),
        migrations.AddField(
            model_name='detalleturno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turno.Turno'),
        ),
    ]
