# Generated by Django 2.1 on 2019-05-30 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creado',
            fields=[
                ('estadoturno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turno.EstadoTurno')),
            ],
            bases=('turno.estadoturno',),
        ),
    ]
