# Generated by Django 2.1 on 2019-05-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0002_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fechaTurno',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
