# Generated by Django 2.1 on 2019-05-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='telefrono',
            new_name='telefono',
        ),
    ]
