# Generated by Django 2.1 on 2019-05-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_auto_20190529_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codevalidator',
            name='code',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
