# Generated by Django 2.1 on 2019-05-29 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCompra', models.DateField(auto_now=True)),
                ('precioTotal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=256)),
                ('fechaDevolucion', models.DateField(auto_now=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pago.Compra')),
            ],
            options={
                'verbose_name': 'Devolucion',
                'verbose_name_plural': 'Devoluciones',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='metodoPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pago.MetodoPago'),
        ),
        migrations.AddField(
            model_name='compra',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turno.Turno'),
        ),
    ]
